### ISSUE TITLE
Exit code: 1

### ISSUE THREAD

**Issue by LaraSQP** [Daylily-Zeleen/GDScript-Formatter#5]
Thank you for developing this addon.

I was able to install it successfully:

```
-- Begin install gdtoolkit.
-- Install gdtoolkit successfully.
```

But I get the following when I try to format a trivial sample script:

```
 Exit code: 1
 Format GDScript failed: res://main.gd
```

This is the script:

```
extends Node

@onready var weapon = $Player/Weapon

enum Align {Horizontal, Vertical}

@export var align = Align.Horizontal

var health = 100

func _ready():
	$Label.text = "hello world"
	$Label.modulate = Color.SEA_GREEN

	print(align)
	
	var a = [1,2,3]
	print(a)
	var b = {"ds":2, 2:1}
	print(b)

func _input(event):
	if event.is_action_pressed("my_action"):
		$Label.modulate = Color.DARK_RED
		jump(health)

	if event.is_action_released("my_action"):
		$Label.modulate = Color.SEA_GREEN

func jump(amount):
	print(amount)

```

There must be something obvious that I'm missing here. Apologies if this is a dumb question.

More messages.

I just restarted Gogot and got the following:

```
Godot Engine v4.2.2.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:63 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  The Command 'GDScript Formatter/Format GDScript' doesn't exists. Unable to remove it.
  GDScript Formatter: The command "gdformat" can't be found in your envrionment.
```

I got the errors below after I doing this: `Project->Tool->GDScript Formatter: Install/Update gdtoolkit`

```
-- Begin install gdtoolkit.
-- Install gdtoolkit successfully.
  This function in this node (/root/@EditorNode@17147/@Panel@13/@VBoxContainer@14/@EditorTitleBar@15/@MenuBar@111/Project/Tools) can only be accessed from either the main thread or a thread group. Use call_deferred() instead.
  This function in this node (/root/@EditorNode@17147/@Panel@13/@VBoxContainer@14/@EditorTitleBar@15/@MenuBar@111/Project/Tools) can only be accessed from either the main thread or a thread group. Use call_deferred() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17147/@Panel@13/@VBoxContainer@14/@EditorTitleBar@15/@MenuBar@111/Project/Tools/@MarginContainer@4047/@ScrollContainer@4048/@Control@4049). Use call_deferred() or call_thread_group() instead.
  This function in this node (/root/@EditorNode@17147/@Panel@13/@VBoxContainer@14/@EditorTitleBar@15/@MenuBar@111/Project/Tools) can only be accessed from the main thread. Use call_deferred() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17147/@Panel@13/@VBoxContainer@14/@EditorTitleBar@15/@MenuBar@111/Project/Tools). Use call_deferred() or call_thread_group() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17147/@Panel@13/@VBoxContainer@14/@EditorTitleBar@15/@MenuBar@111/Project/Tools). Use call_deferred() or call_thread_group() instead.
  This function in this node (/root/@EditorNode@17147/@Panel@13/@VBoxContainer@14/@EditorTitleBar@15/@MenuBar@111/Project/Tools) can only be accessed from the main thread. Use call_deferred() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17147/@Panel@13/@VBoxContainer@14/@EditorTitleBar@15/@MenuBar@111/Project/Tools). Use call_deferred() or call_thread_group() instead.
```

But I get the message below if I do this again: `Project->Tool->GDScript Formatter: Install/Update gdtoolkit`
```
-- Begin install gdtoolkit.
-- Install gdtoolkit successfully.
```

But the format script command still exits with 1 and a fail.

Hopefully, this means something to you.

**Comment by LaraSQP** [comment]
I saw this:

https://github.com/Daylily-Zeleen/GDScript-Formatter/issues/3

So I downloaded the latest script directly from this repository. Same error:

```
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
The Command 'GDScript Formatter/Format GDScript' doesn't exists. Unable to remove it.
GDScript Formatter: The command "gdformat" can't be found in your envrionment.
```

I am using Godot Engine v4.2.2

**Comment by Daylily-Zeleen** [comment]
This seems quite chaotic.

I need to specify that not all scripts can be formatted successfully, for example, multiline lambda. This is due to the limitation of "gdtoolkit", not this plugin.

I had tested your script, it can be formatted successfully.

I guess, your case, the "gdtoolkit" is install successful for some users only, and the "gdformat" command can't be found in your environment.

You can try steps as below.
1. Open a command line and type `gdformat --version` to check the output:

![QQ图片20240525154241](https://github.com/Daylily-Zeleen/GDScript-Formatter/assets/61624558/d3aff16e-8876-4c30-88bb-007af78f0680)

2. If the output is indicate that "gdformat" is not a valid command, executable or bat, you can try to change the `gdformat --verision` to a valid command, for example, `path/to/gdformat --version`, untill the output can provide a correct version.

3. Then set `gdformat_command` to the valid command "path/to/gdformat" in "res://addons/gdscript_formatter/format_preference.tres" and save this resource.

4. Reactivate this plugin.

------------------
By the way, recommend to use latest plugin by download from github (current is v0.1.1).
I make the error messages more accurate and avoid adding format function if the "gdformat" is invalid in latest version.

**Comment by LaraSQP** [comment]
Thank you for the quick reply. It was not installed globally.
